PL/Controllers/DiscoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class DiscoController : Controller
    {
        // GET: Disco
        public ActionResult GetAll()
        {
            ML.Result result=BL.Disco.GetAll();
            ML.Disco disco=new ML.Disco();
            disco.Discos = new List<object>();
            if (result.Correct)
            {
                disco.Discos = result.Objects;
            }
            else
            {
                ViewBag.Message = result.ErrorMessage;

            }
            return View(disco);
        }
        [HttpGet]
        public ActionResult Form(int? IdDisco)
        {
            
            ML.Disco disco = new ML.Disco();
            //ML.Disco disco=new ML.Disco();
            ML.Result resultadoArtista=BL.Artista.GetAll(); 
            ML.Result resultadoGenero=BL.Genero.GetAll(); 
            disco.Artista = new ML.Artista();
            disco.Genero=new ML.Genero();

            
            if (IdDisco != null)//Update
            {
                //ML.Result result=new ML.Result();
                ML.Result result = BL.Disco.GetById(IdDisco.Value);
                if (result.Correct)
                {
                    disco=(ML.Disco)result.Object;
                    disco.Discos = resultadoArtista.Objects;
                    disco.Discos2=resultadoGenero.Objects;
                }
            }
            else//Add
            {
                disco.Discos = resultadoArtista.Objects;
                disco.Discos2 = resultadoGenero.Objects;
            }
            return View(disco);
            //return View(disco1);

        }
        [HttpPost]
        public ActionResult Form(ML.Disco disco)
        {
            //ML.Result result = new ML.Result();
            if (disco.IdDisco==0)//Add
            {
                ML.Result result = BL.Disco.Add(disco);
                if (result.Correct)
                {
                    ViewBag.Mensaje = "Se agrego correctamente";
                }
                else
                {
                    ViewBag.Mensaje = "No se pudo registrar el disco correctamente" + result.ErrorMessage;
                }
            }
            else//Update
            {
                ML.Result result = BL.Disco.Update(disco);
                if (result.Correct)
                {
                    ViewBag.Mensaje = "Actualizado Correctamente";
                }
                else
                {
                    ViewBag.Mensaje = "No se pudo registrar el disco"+ result.ErrorMessage;
                }

            }
            return PartialView("Modal");
        }
        [HttpGet]
        public ActionResult Delete(int IdDisco)
        {
            ML.Result result = BL.Disco.Delete(IdDisco);
           
            if (result.Correct)
            {
                ViewBag.Mensaje = "Eliminado correctamente";
            }
            else
            {
                ViewBag.Mensaje = "No se pudo eliminar correctamente "+result.ErrorMessage;
            }
            return PartialView("Modal");
        }
    }
}

PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Views/Disco/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

PL/Views/Disco/Form.cshtml
@model ML.Disco
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrar Discos</h2>
<h5>Llena los campos para registrar el disco</h5>
<hr /> 
<div class="container">
    @using (Html.BeginForm("Form", "Disco", FormMethod.Post, new { enctype = "multipart/form-data" })) { 
        <div class="row">
            @Html.HiddenFor(model => model.IdDisco)

            @*@Html.LabelFor(model => Model.IdDisco)
                @Html.TextBoxFor(model => Model.IdDisco, new { @class = "form-control visually-hidden" })*@
            <div class="col-md-3">
                @Html.LabelFor(model => Model.Titulo)
                @Html.TextBoxFor(model => Model.Titulo, new { @class = "form-control" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => Model.Artista.IdArtista)
                @Html.DropDownListFor(model => Model.Artista.IdArtista, new SelectList(Model.Discos, "IdArtista", "NombreArtista"), "Selecciona un artista", new { @class = "form-control" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => Model.Genero.IdGenero)
                @Html.DropDownListFor(model => Model.Genero.IdGenero, new SelectList(Model.Discos2, "IdGenero", "NombreGenero"), "Selecciona un genero", new { @class = "form-control" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => Model.Duracion)
                @Html.TextBoxFor(model => Model.Duracion, new { @class = "form-control" })
            </div>

        </div>
    <div class="row">
        <div class="col-md-3">
            @Html.LabelFor(model => Model.Anio)
            @Html.TextBoxFor(model => Model.Anio, new { @class = "form-control" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => Model.Distribuidora)
            @Html.TextBoxFor(model => Model.Distribuidora, new { @class = "form-control" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => Model.Ventas)
            @Html.TextBoxFor(model => Model.Ventas, new { @class = "form-control" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => Model.Disponibilidad)
            @Html.TextBoxFor(model => Model.Disponibilidad, new { @class = "form-control" })
        </div>
    </div>
    <hr />
    <div class="row">
        <input class="btn btn-success" type="submit" name="name" value="Guardar" />
        @Html.ActionLink("Cancelar", "GetAll", "Disco", htmlAttributes: new { @class = "btn btn-danger" })

    </div>
    }
</div>

PL/Views/Disco/GetAll.cshtml
@model ML.Disco
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetAll</h2>
<hr />
<a class="btn btn-success col-md-2" href="@Url.Action("Form","Disco")">Agregar</a>
<br />
<hr />
<div class="container">
    <div class="row">
        @if (Model.Discos != null)
        {
            <table class="table table-bordered table-responsive">
                <thead>
                    <tr>
                        <th>Id Disco</th>
                        <th>Titulo</th>
                        <th>Artista</th>
                        <th>Genero</th>
                        <th>Duración</th>
                        <th>Año</th>
                        <th>Distribuidora</th>
                        <th>Ventas</th>
                        <th>Disponibilidad</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.Disco disco in Model.Discos)
                    {
                    <tr>
                        <td class="col-md-1">@disco.IdDisco</td>
                        <td class="col-md-1">@disco.Titulo</td>
                        <td class="col-md-1">@disco.Artista.NombreArtista</td>
                        <td class="col-md-1">@disco.Genero.NombreGenero</td>
                        <td class="col-md-1">@disco.Duracion</td>
                        <td class="col-md-1">@disco.Anio</td>
                        <td class="col-md-1">@disco.Distribuidora</td>
                        <td class="col-md-1">@disco.Ventas</td>
                        <td class="col-md-1">@disco.Disponibilidad</td>
                        <td class="col-md-1">
                            <div class="row">
                                <div class="col-md-12">
                                    <a class="btn btn-danger" href="@Url.Action("Delete","Disco",new {IdDisco=disco.IdDisco})">Eliminar</a>
                                </div>
                                <br />
                                <div class="col-md-3">
                                    <a class="btn btn-warning" href="@Url.Action("Form","Disco",new {IdDisco=disco.IdDisco})">Actualizar</a>
                                </div>
                            </div>

                            
                        </td>
                    </tr>    
                    }
                    
                </tbody>

            </table>
        }
        else
        {
            <h1>No hay registros</h1>
        }

    </div>
</div>

PL/Views/Disco/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@
                @Html.ActionLink("Continuar", "GetAll", "Disco", htmlAttributes: new { @class = "btn btn-danger" })


            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Discos", "GetAll", "Disco")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>